train:
  - name: FIELD
    im_dir: ./data/FIELD/train/images
    gt_dir: ./data/FIELD/train/masks
    im_ext: .JPG
    gt_ext: .png
valid:
  - name: FIELD
    im_dir: ./data/FIELD/val/images
    gt_dir: ./data/FIELD/val/masks
    im_ext: .JPG
    gt_ext: .png