defaults:
  - experiments: default
  - _self_

world_size: 1 # number of distributed processes
dist_url: env:// # url used to set up distributed training
rank: 0 # number of distributed processes
local_rank: 0 # local rank for dist
find_unused_params: false
gpu: None
distributed: false
dist_backend: nccl